version: '24.0.5'
services:
  # depends_on:
  #       db:
  #           condition: service_healthy
  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
       POSTGRES_PASSWORD: ${DB_PASSWORD}
       POSTGRES_USER: ${DB_USER}
       POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432

    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      timeout: 45s
      interval: 10s
      retries: 10

volumes:
      pgdata:



     
  

   
